### ISSUE TITLE
a conflict with indent

### ISSUE THREAD

**Issue by maxfl** [machakann/vim-sandwich#6] opened 2015-07-14 02:00 UTC
I've disabled all the plugins except vim-sandwich with default configuration and with 'filetype plugin indent on'. I edit the test.tex file with the following contents:
```tex
    test
```
The main point is spaces before the 'test'. If I select 'test' by 'viw' and the try to surround it by something with 'sa[' the result is the following:
```tex
te[st]
```
Apparently vim reindents the line before sandwich wraps the selection. If I do not call 'filetype plugin indent on' the behaviour is normal.

**Comment by machakann** [comment] 2015-07-14 05:40
OK, I reproduced. You are right, it is because of the autoindent feature of vim (I do not mean only `autoindent` option, all this kind of options `autoindent`, `smartindent`, `cindent`, `indentexpr`, especially `indentexpr` option relates to this case.)

The problem is that the autoindent in tex is ignited when '[' and ']' is typed in anywhere. Temporary this problem could be solved using autocmd.
```vim
autocmd User OperatorSandwichAddPre,OperatorSandwichReplacePre if &ft =~# '\%(plain\)\?tex' | set indentkeys-=] | endif
autocmd User OperatorSandwichAddPost,OperatorSandwichReplacePost if &ft=~# '\%(plain\)\?tex' | set indentkeys+=] | endif

" You might need these lines additionally
autocmd User OperatorSandwichAddPre,OperatorSandwichReplacePre if &ft =~# '\%(plain\)\?tex' | set indentkeys-=[ | endif
autocmd User OperatorSandwichAddPost,OperatorSandwichReplacePost if &ft=~# '\%(plain\)\?tex' | set indentkeys+=[ | endif
```

However I think this is general problem. Since `'buns'` can include line break `\n`, thus I do not want to turn off autoindent simply. I am going to give new options for indent. Please keep opened this issue. Thanks!

**Comment by maxfl** [comment] 2015-07-14 06:37
Thank you for looking at this. As I see for latex almost all the keys trigger the autoindent. There for I can at least try to disable them permanently until the issue is resolved.

**Comment by machakann** [comment] 2015-07-14 15:16
Now I am imagining to implement new options like:

```
autoindent
	This option is used in order to control vim autoindent feature in an
	operator action. The value is an integer and the numbers from 1 to 4
	correspond to vim built-in options 'autoindent', 'smartindent',
	'cindent' and 'indentexpr' respectively. If the value is 0, then never
	use autoindent function. If the value is negative integer, then it
	does not change any setting, just use the current autoindent setting.

	  * -n : Current settings
	  *  0 : 'noautoindent', 'nosmartindent', 'nocindent', 'noindentexpr'
	  *  1 : 'autoindent'
	  *  2 : 'smartindent'
	  *  3 : 'cindent'
	  *  4 : 'indentexpr'

	If "buns" include line breaks, it would be better to think about this
	option. Practically the value 1 ('autoindent') would be helpful in
	many cases, at least it is easier to expect its result. The other
	positive integers sometimes cause unexpected results, use them with
	cares.
>
	let g:sandwich#recipes += [
	  \   {'buns': ['{', '}'], 'motionwise': ['line'], 'autoindent': 3},
	  \ ]
<
	Default values
	  * add
	    - char : 1
	    - line : 1
	    - block: 1
	  * replace
	    - char : 1
	    - line : 1
	    - block: 1



indentkeys
indentkeys+
indentkeys-
	These options are used in order to change 'indentkeys' or 'cinkeys'
	option temporary in an action. The format is identical to 'cinkeys'.
	The value of "indentkeys" is set as written directly, as if the string
	was assigned to the {value} of |:set| indentkeys={value}. Similar to
	that, "indentkeys+" and "indentkeys-" is set as if they are assigned
	to the {value} of |:set| indentkeys+={value} or
	|:set| indentkeys-={value}. See |:set+=| and |:set-=|. One thing there
	is a difference from |:set-=| is that user does not need to mind about
	the order of items. |:set-=| depends on the order of items.
>
	:set indentkeys?    " -> 0{,0},:,0#,!^F,o,O,e
	:set indentkeys-=0},0{
	:set indentkeys?    " -> 0{,0},:,0#,!^F,o,O,e

	" '0{' and '0}' are not removed,
	" because there is *not* the strings '0},0{'

	:set indentkeys-=0}
	:set indentkeys?    " -> 0{,:,0#,!^F,o,O,e
	:set indentkeys-=0{
	:set indentkeys?    " -> :,0#,!^F,o,O,e
<
	As for the local option "indentkeys-", operators parse it by
	themselves for remove items. Therefore user does not need to mind
	about the order of items. If 'indentexpr' is empty and 'cindent' is
	valid, these options are applied to 'cinkeys'.
>
	let g:sandwich#recipes += [
	  \   {'buns': ['[', ']'], 'filetype': ['tex'], 'indentkeys-': '[,]'},
	  \ ]
<
	Default values
	  * add
	    - char : ''
	    - line : ''
	    - block: ''
	  * replace
	    - char : ''
	    - line : ''
	    - block: ''
```

I have not locked in yet. Any suggestions are welcome. Additionally, since I am non-native speaker, if the description is not clear please tell me :)

**Comment by maxfl** [comment] 2015-07-14 15:27
Looks very nice. As for English, it's mostly clear for me (non-english speaker as well). Only one place is a bit difficult to understand: 
```
As for the local option "indentkeys-", operators parse it by themselves for remove items.
```
And I would also replace 'Therefore user does not need to mind' to 'Therefore user does not need to care about'.

**Comment by machakann** [comment] 2015-07-14 16:38
Thank you!

**Comment by lervag** [comment] 2015-07-14 20:10
I agree that this looks good. A couple of suggestions/questions:

1. Would it not make sense to use the current indent options as default values, i.e. `autoindent < 0`?
2. "The other positive integers sometimes cause unexpected results, use them with cares." -> "... sometime ... care."

**Comment by machakann** [comment] 2015-07-15 12:04
Thanks for all your comments. I revised the documents.
```
	In contrast to that, user does not need to care about the order of
	items for the local option "indentkeys-". Simply list the items to be
	removed.
>
	let g:sandwich#recipes += [
	  \   {'buns': ['[', ']'], 'filetype': ['tex'], 'indentkeys-': '[,]'}
	  \ ]

	" This is same as the above
	"let g:sandwich#recipes += [
	"  \   {'buns': ['[', ']'], 'filetype': ['tex'], 'indentkeys-': '],['}
	"  \ ]
<
```
```
The other positive integers sometime cause unexpected results, use them with care.
```

The first question from @lervag is important. I agree that it is natural to set a negative integer to "autoindent" option as default. However it seems less problemsome to use 1 as default.

I would like to make it useful with default settings as possible. Additionally, this option would affect to the behavior of linewise additions also, it might have rather bigger effects than I expected. At this moment, they are equally probable. I will decide carefully.

**Comment by lervag** [comment] 2015-07-15 12:34
Good, I think your decision will be good. (If not, and if I have a good argument against it, then I will complain here later. :) )

**Comment by maxfl** [comment] 2015-07-17 01:34
seems good!

**Comment by machakann** [comment] 2015-07-17 14:24
Hi, thanks for waiting! Now I pushed the latest version (fa6e7412d55011c8740bb5c8967c644930f47625).
I have taken much time to check the behavior, but it looks OK.

Finally, I determined to set 1 for `autoindent` option as default. Because `sandwich.vim` edit texts in a different way from the normal. It makes that the other options is not practical, unfortunately, at this moment. Please see #7. But, anyway, I believe that many autoindent problems has been solved in this issue with new options. Please check it!

**Comment by machakann** [comment] 2015-07-17 14:46
I slightly changed the specs. The valid value for `autoindent` option is now -n ~ 3, 4 is obsoleted. Because autoindent features are exclusive each other and `'indentexpr'` has highest priority, thus negative values could be used for `'indentexpr'` too, if it is not empty.

**Comment by maxfl** [comment] 2015-07-17 20:23
@machakann, I've modified my mappings. It seem to be working ok on simple cases. I will write if I encounter any problems.

Thank you!

**Comment by machakann** [comment] 2015-07-18 09:02
@maxfl Anytime! Please keep opening this issue, I will wait and see whether it works well for a while. After about a few weeks, I will close this issue. Of course you can reopen even after I close if you found some problems. Thanks!

**Closed** 2015-08-09 14:13 UTC
Labels: bug, enhancement
